---
title: "lab01"
author: "Leopoldo Gutierre"
date: "25 de janeiro de 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Funções

Função Moeda e exemplo
```{r}
moeda <- function(p) {
  return((runif(1)<=p)*1)
}
moeda(0.5)
```

Função Moedas e exemplo
```{r}
moedas <- function(n,p) {
  return((runif(n)<=p)*1)
}

mean(moedas(1000000,0.4))
```


Função proporcao e exemplo
```{r}
proporcao <- function(resultados){
  return(mean(resultados))
}
proporcao(moedas(1000000,0.4))
```

Função simulacao
```{r}
simulacao <- function(k,n,p){
  x  <-  rep(0,k)
  for(i in 1:k){
    x[i]  <-  proporcao(moedas(n,p))
  }
  return(x)
} 
dados <- data.frame(simulacao(10,10000,0.5))
names(dados) <- "simul"
dados
```


## Histogramas

Segue uma sequência de gráficos para os seguintes pares (n,p): (10,0.5);(1000,0.5);(1000000,0.5) e (10,0.8);(1000,0.8);(1000000,0.8)

```{r hist, echo=FALSE}
library(ggplot2)
pp = c(100, 1000, 10000)
nn = c(1,1,1)
xx1=matrix(c(pp,0.5*nn),nrow=3,ncol=2)
xx2=matrix(c(pp,0.8*nn),nrow=3,ncol=2)
xx3 = rbind(xx1,xx2)
k = 1000

for (i in 1:6) {
  n <- xx3[i,1]
  p <- xx3[i,2]
  dados <- data.frame(simulacao(k,n,p))
  names(dados) <- "simul"
  descr <- paste("Histograma para (n,p) = (",n,",",p,")")
  plott <- qplot(dados$simul,
        geom="histogram",
        main = descr,
        bins = 50,
        xlab = "Proporção",  
        ylab = "Frequência",  
        fill=I("blue"), 
        col=I("red"), 
        alpha=I(.2))
  print(plott)
}

```




A medida que n cresce a distribuição se aproxima de uma normal.
